
import type { Component, LogEntry } from './types';
import { subDays } from 'date-fns';

export const mockComponents: Component[] = [
  {
    id: '1',
    name: 'Resistor (100 Ohm, 1/4W)',
    manufacturer: 'Generic',
    partNumber: 'R100_1/4W',
    description: 'Carbon Film, 5% Tolerance',
    quantity: 500,
    location: 'R-Shelf-A1',
    unitPrice: 0.5,
    datasheetUrl: '#',
    category: 'Resistors',
    lowStockThreshold: 100,
    lastOutwardDate: subDays(new Date(), 10).toISOString(),
  },
  {
    id: '2',
    name: 'Resistor (1k Ohm, 1/4W)',
    manufacturer: 'Generic',
    partNumber: 'R1K_1/4W',
    description: 'Carbon Film, 5% Tolerance',
    quantity: 500,
    location: 'R-Shelf-A1',
    unitPrice: 0.5,
    datasheetUrl: '#',
    category: 'Resistors',
    lowStockThreshold: 100,
    lastOutwardDate: subDays(new Date(), 15).toISOString(),
  },
  {
    id: '3',
    name: 'Resistor (10k Ohm, 1/4W)',
    manufacturer: 'Generic',
    partNumber: 'R10K_1/4W',
    description: 'Carbon Film, 5% Tolerance',
    quantity: 500,
    location: 'R-Shelf-A1',
    unitPrice: 0.5,
    datasheetUrl: '#',
    category: 'Resistors',
    lowStockThreshold: 100,
    lastOutwardDate: subDays(new Date(), 20).toISOString(),
  },
  {
    id: '4',
    name: 'Resistor (4.7 Ohm, 1W)',
    manufacturer: 'Generic',
    partNumber: 'R4.7_1W',
    description: 'Metal Film, 1% Tolerance',
    quantity: 150,
    location: 'R-Shelf-A2',
    unitPrice: 1.2,
    datasheetUrl: '#',
    category: 'Resistors',
    lowStockThreshold: 30,
    lastOutwardDate: subDays(new Date(), 120).toISOString(),
  },
  {
    id: '5',
    name: 'Ceramic Cap (0.1uF, 50V)',
    manufacturer: 'Generic',
    partNumber: 'C0.1UF_50V_CER',
    description: 'Ceramic Disc Capacitor',
    quantity: 800,
    location: 'C-Bin-B1',
    unitPrice: 0.8,
    datasheetUrl: '#',
    category: 'Capacitors',
    lowStockThreshold: 200,
    lastOutwardDate: subDays(new Date(), 5).toISOString(),
  },
  {
    id: '6',
    name: 'Electrolytic Cap (100uF, 25V)',
    manufacturer: 'Generic',
    partNumber: 'C100UF_25V_EL',
    description: 'Radial Electrolytic Capacitor',
    quantity: 200,
    location: 'C-Bin-B2',
    unitPrice: 2.5,
    datasheetUrl: '#',
    category: 'Capacitors',
    lowStockThreshold: 50,
    lastOutwardDate: subDays(new Date(), 45).toISOString(),
  },
  {
    id: '7',
    name: 'Tantalum Cap (10uF, 16V)',
    manufacturer: 'KEMET',
    partNumber: 'T491A106K016AT',
    description: 'SMD Tantalum Capacitor',
    quantity: 100,
    location: 'C-Bin-B3',
    unitPrice: 5,
    datasheetUrl: '#',
    category: 'Capacitors',
    lowStockThreshold: 20,
    lastOutwardDate: subDays(new Date(), 150).toISOString(),
  },
  {
    id: '8',
    name: 'Inductor (10uH)',
    manufacturer: 'Generic',
    partNumber: 'L10UH',
    description: 'Radial Lead Inductor',
    quantity: 100,
    location: 'L-Bin-C1',
    unitPrice: 3,
    datasheetUrl: '#',
    category: 'Inductors',
    lowStockThreshold: 25,
    lastOutwardDate: subDays(new Date(), 60).toISOString(),
  },
  {
    id: '9',
    name: '1N4007 Diode',
    manufacturer: 'Fairchild',
    partNumber: '1N4007',
    description: 'Rectifier Diode, 1A, 1000V',
    quantity: 300,
    location: 'D-Bin-D1',
    unitPrice: 1,
    datasheetUrl: '#',
    category: 'Diodes',
    lowStockThreshold: 75,
    lastOutwardDate: subDays(new Date(), 8).toISOString(),
  },
  {
    id: '10',
    name: 'Zener Diode (5.1V, 0.5W)',
    manufacturer: 'ON Semiconductor',
    partNumber: '1N5231B',
    description: 'Zener Diode',
    quantity: 150,
    location: 'D-Bin-D2',
    unitPrice: 1.5,
    datasheetUrl: '#',
    category: 'Diodes',
    lowStockThreshold: 30,
    lastOutwardDate: subDays(new Date(), 95).toISOString(),
  },
  {
    id: '11',
    name: 'NPN Transistor (BC547)',
    manufacturer: 'NXP',
    partNumber: 'BC547B',
    description: 'NPN BJT, General Purpose',
    quantity: 200,
    location: 'T-Tray-E1',
    unitPrice: 1.2,
    datasheetUrl: '#',
    category: 'Transistors',
    lowStockThreshold: 50,
    lastOutwardDate: subDays(new Date(), 180).toISOString(),
  },
  {
    id: '12',
    name: 'MOSFET (IRF540N)',
    manufacturer: 'Infineon',
    partNumber: 'IRF540N',
    description: 'N-Channel Power MOSFET',
    quantity: 50,
    location: 'T-Tray-E2',
    unitPrice: 25,
    datasheetUrl: '#',
    category: 'Transistors',
    lowStockThreshold: 10,
    lastOutwardDate: subDays(new Date(), 22).toISOString(),
  },
  {
    id: '13',
    name: 'NE555 Timer IC',
    manufacturer: 'Texas Instruments',
    partNumber: 'NE555P',
    description: 'Precision Timer IC',
    quantity: 80,
    location: 'IC-Box-F1',
    unitPrice: 8,
    datasheetUrl: '#',
    category: 'Integrated Circuits (ICs)',
    lowStockThreshold: 20,
    lastOutwardDate: subDays(new Date(), 40).toISOString(),
  },
  {
    id: '14',
    name: 'LM358 Op-Amp',
    manufacturer: 'STMicroelectronics',
    partNumber: 'LM358N',
    description: 'Dual Op-Amp',
    quantity: 100,
    location: 'IC-Box-F2',
    unitPrice: 6,
    datasheetUrl: '#',
    category: 'Integrated Circuits (ICs)',
    lowStockThreshold: 25,
    lastOutwardDate: subDays(new Date(), 55).toISOString(),
  },
  {
    id: '15',
    name: 'ATmega328P (DIP)',
    manufacturer: 'Microchip',
    partNumber: 'ATMEGA328P-PU',
    description: 'Microcontroller, 8-bit',
    quantity: 30,
    location: 'IC-Box-F3',
    unitPrice: 150,
    datasheetUrl: '#',
    category: 'Integrated Circuits (ICs)',
    lowStockThreshold: 5,
    lastOutwardDate: subDays(new Date(), 70).toISOString(),
  },
  {
    id: '16',
    name: 'ESP32-WROOM-32U',
    manufacturer: 'Espressif',
    partNumber: 'ESP32-WROOM-32U',
    description: 'Wi-Fi & Bluetooth Module',
    quantity: 20,
    location: 'IC-Box-F4',
    unitPrice: 200,
    datasheetUrl: '#',
    category: 'Integrated Circuits (ICs)',
    lowStockThreshold: 3,
    lastOutwardDate: subDays(new Date(), 2).toISOString(),
  },
  {
    id: '17',
    name: 'Male Header (2.54mm, 40-pin)',
    manufacturer: 'Generic',
    partNumber: 'HDR-M-2.54-40',
    description: 'Single Row Pin Header',
    quantity: 100,
    location: 'Conn-Drawer-G1',
    unitPrice: 3.5,
    datasheetUrl: '#',
    category: 'Connectors',
    lowStockThreshold: 20,
    lastOutwardDate: subDays(new Date(), 12).toISOString(),
  },
  {
    id: '18',
    name: 'JST-XH Connector (2-pin)',
    manufacturer: 'JST',
    partNumber: 'B2B-XH-A(LF)(SN)',
    description: 'Through-hole, 2-pin',
    quantity: 50,
    location: 'Conn-Drawer-G2',
    unitPrice: 4,
    datasheetUrl: '#',
    category: 'Connectors',
    lowStockThreshold: 10,
    lastOutwardDate: subDays(new Date(), 18).toISOString(),
  },
  {
    id: '19',
    name: 'DHT11 Temperature/Humidity',
    manufacturer: 'Aosong',
    partNumber: 'DHT11',
    description: 'Digital Temperature & Humidity Sensor',
    quantity: 15,
    location: 'Sensor-Bin-H1',
    unitPrice: 50,
    datasheetUrl: '#',
    category: 'Sensors',
    lowStockThreshold: 3,
    lastOutwardDate: subDays(new Date(), 99).toISOString(),
  },
  {
    id: '20',
    name: 'Photoresistor (LDR)',
    manufacturer: 'Generic',
    partNumber: 'GL5516',
    description: 'Light Dependent Resistor',
    quantity: 30,
    location: 'Sensor-Bin-H2',
    unitPrice: 7,
    datasheetUrl: '#',
    category: 'Sensors',
    lowStockThreshold: 5,
    lastOutwardDate: subDays(new Date(), 3).toISOString(),
  },
  {
    id: '21',
    name: 'Arduino Uno R3',
    manufacturer: 'Arduino',
    partNumber: 'A000066',
    description: 'Development Board',
    quantity: 5,
    location: 'DevBoard-Rack-I1',
    unitPrice: 800,
    datasheetUrl: '#',
    category: 'Microcontrollers/Dev Boards',
    lowStockThreshold: 1,
    lastOutwardDate: subDays(new Date(), 88).toISOString(),
  },
  {
    id: '22',
    name: 'Raspberry Pi Zero W',
    manufacturer: 'Raspberry Pi Found.',
    partNumber: 'RPI0W',
    description: 'Single-board Computer',
    quantity: 3,
    location: 'DevBoard-Rack-I2',
    unitPrice: 1200,
    datasheetUrl: '#',
    category: 'Microcontrollers/Dev Boards',
    lowStockThreshold: 1,
    lastOutwardDate: subDays(new Date(), 200).toISOString(),
  },
  {
    id: '23',
    name: 'Tactile Push Button (6x6mm)',
    manufacturer: 'Generic',
    partNumber: 'BTN-TACT-6X6',
    description: 'Momentary Tactile Switch',
    quantity: 100,
    location: 'Switch-Box-J1',
    unitPrice: 1,
    datasheetUrl: '#',
    category: 'Switches/Buttons',
    lowStockThreshold: 25,
    lastOutwardDate: subDays(new Date(), 4).toISOString(),
  },
  {
    id: '24',
    name: 'SPDT Slide Switch',
    manufacturer: 'Generic',
    partNumber: 'SW-SPDT-SLIDE',
    description: 'Single Pole Double Throw Slide Switch',
    quantity: 40,
    location: 'Switch-Box-J2',
    unitPrice: 3,
    datasheetUrl: '#',
    category: 'Switches/Buttons',
    lowStockThreshold: 10,
    lastOutwardDate: subDays(new Date(), 28).toISOString(),
  },
  {
    id: '25',
    name: 'Red LED (5mm)',
    manufacturer: 'Generic',
    partNumber: 'LED-RED-5MM',
    description: 'Standard Red LED',
    quantity: 0,
    location: 'LED-Tray-K1',
    unitPrice: 0.8,
    datasheetUrl: '#',
    category: 'LEDs/Displays',
    lowStockThreshold: 50,
    lastOutwardDate: subDays(new Date(), 35).toISOString(),
  },
  {
    id: '26',
    name: '16x2 LCD Display',
    manufacturer: 'Generic',
    partNumber: 'LCD1602',
    description: 'Character LCD Module',
    quantity: 10,
    location: 'LCD-Box-K2',
    unitPrice: 150,
    datasheetUrl: '#',
    category: 'LEDs/Displays',
    lowStockThreshold: 2,
    lastOutwardDate: subDays(new Date(), 75).toISOString(),
  },
  {
    id: '27',
    name: 'Jumper Wires (M-M, 40pc)',
    manufacturer: 'Generic',
    partNumber: 'JMP-MM-40',
    description: 'Male-to-Male Jumper Wires, assorted',
    quantity: 10,
    location: 'Cable-Bag-L1',
    unitPrice: 80,
    datasheetUrl: '#',
    category: 'Cables/Wires',
    lowStockThreshold: 2,
    lastOutwardDate: subDays(new Date(), 1).toISOString(),
  },
];


const generateLogs = (): LogEntry[] => {
  const logs: LogEntry[] = [];
  const users = [
    { name: 'Admin User', avatar: 'https://placehold.co/40x40.png' },
    { name: 'Tech User', avatar: 'https://placehold.co/40x40.png' },
    { name: 'Researcher User', avatar: 'https://placehold.co/40x40.png' },
  ];
  
  for (let i = 0; i < 50; i++) {
    const component = mockComponents[i % mockComponents.length];
    const user = users[i % users.length];
    const inwardQty = Math.floor(Math.random() * 20) + 5;
    const outwardQty = Math.floor(Math.random() * 10) + 1;

    // Inward
    logs.push({
      id: `log-in-${i}`,
      user,
      action: 'Added',
      componentName: component.name,
      componentId: component.id,
      timestamp: subDays(new Date(), i).toISOString(),
      details: `Added ${inwardQty} units.`,
      quantity: inwardQty,
    });
    
    // Outward (for some)
    if (i % 2 === 0) {
       logs.push({
        id: `log-out-${i}`,
        user,
        action: 'Issued',
        componentName: component.name,
        componentId: component.id,
        timestamp: subDays(new Date(), i).toISOString(),
        details: `Issued ${outwardQty} units for a project.`,
        quantity: outwardQty,
      });
    }
  }
  return logs;
}


export const mockLogs: LogEntry[] = generateLogs();
